[tool.poetry]
name = "ex1"
version = "0.1.0"
description = "Module 08 - Exercise 01"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "3.0.1"
numpy = "2.4.2"
matplotlib = "3.10.8"
